### ISSUE TITLE
Hide password characters when typing them in

### ISSUE THREAD

**Issue by ajkblue** [compl3x/parlieu#3]
When typing in the password, use `type="password"` in the password field so the characters are hidden on [Line 37 of index.tpl](https://github.com/compl3x/parlieu/blob/ddd655f1c72ea66c6ee980cb922a59603c5f6543/templates/index.tpl#L37) and on [Line 30 of vindex.tpl](https://github.com/compl3x/parlieu/blob/09e426d3786b3f4cf689aacc63b8593f4c14f959/v/templates/vindex.tpl#L30).

**Comment by compl3x** [comment]
Hey ajkblue,

Good eye, I was meaning to do this but it slipped my mind.

Fixed 8505799d284e4df0afd1785a656f4dee9a539062
